export const INDIAN_FOOD_DATABASE = [
  { name: 'Apple', calories: 95, protein: 0.5, carbs: 25, fat: 0.3, unit: 'medium' },
  { name: 'Banana', calories: 105, protein: 1.3, carbs: 27, fat: 0.3, unit: 'medium' },
  { name: 'Orange', calories: 62, protein: 1.2, carbs: 15, fat: 0.2, unit: 'medium' },
  { name: 'Grapes', calories: 69, protein: 0.7, carbs: 18, fat: 0.2, unit: 'cup' },
  { name: 'Strawberry', calories: 49, protein: 1, carbs: 12, fat: 0.5, unit: 'cup' },
  { name: 'Blueberry', calories: 84, protein: 1.1, carbs: 21, fat: 0.5, unit: 'cup' },
  { name: 'Mango', calories: 202, protein: 2.8, carbs: 50, fat: 1.3, unit: 'medium' },
  { name: 'Pineapple', calories: 82, protein: 0.9, carbs: 22, fat: 0.2, unit: 'cup' },
  { name: 'Watermelon', calories: 86, protein: 1.7, carbs: 22, fat: 0.4, unit: 'wedge' },
  { name: 'Peach', calories: 59, protein: 1.4, carbs: 14, fat: 0.4, unit: 'medium' },
  { name: 'Broccoli', calories: 55, protein: 3.7, carbs: 11, fat: 0.6, unit: 'cup' },
  { name: 'Spinach', calories: 7, protein: 0.9, carbs: 1.1, fat: 0.1, unit: 'cup' },
  { name: 'Carrot', calories: 52, protein: 1.2, carbs: 12, fat: 0.3, unit: 'medium' },
  { name: 'Tomato', calories: 22, protein: 1.1, carbs: 4.8, fat: 0.2, unit: 'medium' },
  { name: 'Cucumber', calories: 16, protein: 0.7, carbs: 3.8, fat: 0.1, unit: 'medium' },
  { name: 'Bell Pepper (Red)', calories: 37, protein: 1.2, carbs: 9, fat: 0.4, unit: 'medium' },
  { name: 'Onion', calories: 44, protein: 1.2, carbs: 10, fat: 0.1, unit: 'medium' },
  { name: 'Potato', calories: 161, protein: 4.3, carbs: 37, fat: 0.2, unit: 'medium' },
  { name: 'Sweet Potato', calories: 112, protein: 2, carbs: 26, fat: 0.2, unit: 'medium' },
  { name: 'Chicken Breast', calories: 165, protein: 31, carbs: 0, fat: 3.6, unit: '100g' },
  { name: 'Salmon', calories: 208, protein: 20, carbs: 0, fat: 13, unit: '100g' },
  { name: 'Egg (Large)', calories: 78, protein: 6, carbs: 0.6, fat: 5, unit: '1 pc' },
  { name: 'Tofu (Firm)', calories: 76, protein: 8, carbs: 1.9, fat: 4.8, unit: '100g' },
  { name: 'Lentils (Cooked)', calories: 116, protein: 9, carbs: 20, fat: 0.4, unit: 'cup' },
  { name: 'Chickpeas (Cooked)', calories: 164, protein: 8.9, carbs: 27, fat: 2.6, unit: 'cup' },
  { name: 'Brown Rice (Cooked)', calories: 216, protein: 5, carbs: 45, fat: 1.8, unit: 'cup' },
  { name: 'Quinoa (Cooked)', calories: 222, protein: 8, carbs: 39, fat: 3.6, unit: 'cup' },
  { name: 'Oats (Cooked)', calories: 150, protein: 5, carbs: 27, fat: 2.5, unit: 'cup' },
  { name: 'Whole Wheat Bread', calories: 82, protein: 4, carbs: 14, fat: 1, unit: 'slice' },
  { name: 'Almonds', calories: 164, protein: 6, carbs: 6, fat: 14, unit: '23 nuts' },
  { name: 'Walnuts', calories: 185, protein: 4, carbs: 4, fat: 18, unit: '7 nuts' },
  { name: 'Avocado', calories: 160, protein: 2, carbs: 9, fat: 15, unit: 'half' },
  { name: 'Olive Oil', calories: 120, protein: 0, carbs: 0, fat: 14, unit: 'tbsp' },
  { name: 'Greek Yogurt (Plain)', calories: 100, protein: 17, carbs: 6, fat: 0, unit: 'cup' },
  { name: 'Milk (2% Fat)', calories: 122, protein: 8, carbs: 12, fat: 5, unit: 'cup' },
  { name: 'Cottage Cheese (Low Fat)', calories: 163, protein: 28, carbs: 6, fat: 2.3, unit: 'cup' },
  { name: 'Cheddar Cheese', calories: 113, protein: 7, carbs: 0.4, fat: 9, unit: 'slice' },
  { name: 'Butter', calories: 102, protein: 0.1, carbs: 0, fat: 11, unit: 'tbsp' },
  { name: 'Peanut Butter', calories: 188, protein: 8, carbs: 7, fat: 16, unit: '2 tbsp' },
  { name: 'Coffee (Black)', calories: 2, protein: 0.3, carbs: 0, fat: 0, unit: 'cup' },
  { name: 'Green Tea', calories: 0, protein: 0, carbs: 0, fat: 0, unit: 'cup' },
  { name: 'Apple Juice', calories: 113, protein: 0.3, carbs: 28, fat: 0.1, unit: 'cup' },
  { name: 'Orange Juice', calories: 112, protein: 1.7, carbs: 26, fat: 0.5, unit: 'cup' },
  { name: 'Coca-Cola', calories: 140, protein: 0, carbs: 39, fat: 0, unit: 'can' },
  { name: 'Pizza (Cheese)', calories: 285, protein: 12, carbs: 36, fat: 10, unit: 'slice' },
  { name: 'Hamburger', calories: 250, protein: 12, carbs: 30, fat: 9, unit: '1 pc' },
  { name: 'French Fries', calories: 365, protein: 4, carbs: 48, fat: 17, unit: 'medium' },
  { name: 'Chocolate Bar', calories: 237, protein: 2.5, carbs: 26, fat: 14, unit: '1 bar' },
  { name: 'Ice Cream (Vanilla)', calories: 207, protein: 3.5, carbs: 28, fat: 11, unit: 'cup' },
  { name: 'Donut', calories: 260, protein: 3, carbs: 30, fat: 14, unit: '1 pc' },
  { name: 'Cookie (Chocolate Chip)', calories: 160, protein: 2, carbs: 21, fat: 8, unit: '1 pc' },
  { name: 'Pasta (Cooked)', calories: 221, protein: 8, carbs: 43, fat: 1.3, unit: 'cup' },
  { name: 'White Rice (Cooked)', calories: 205, protein: 4.3, carbs: 45, fat: 0.4, unit: 'cup' },
  { name: 'Shrimp (Cooked)', calories: 85, protein: 20, carbs: 0.2, fat: 0.5, unit: '100g' },
  { name: 'Pork Chop', calories: 231, protein: 25, carbs: 0, fat: 14, unit: '100g' },
  { name: 'Beef Steak', calories: 271, protein: 25, carbs: 0, fat: 18, unit: '100g' },
  { name: 'Sausage', calories: 346, protein: 12, carbs: 1.5, fat: 32, unit: '100g' },
  { name: 'Bacon', calories: 541, protein: 37, carbs: 0, fat: 42, unit: '100g' },
  { name: 'Ham', calories: 145, protein: 21, carbs: 1, fat: 6, unit: '100g' },
  { name: 'Turkey Breast', calories: 135, protein: 30, carbs: 0, fat: 1.5, unit: '100g' },
  { name: 'Cod', calories: 82, protein: 18, carbs: 0, fat: 0.7, unit: '100g' },
  { name: 'Pomegranate', calories: 83, protein: 1.7, carbs: 18, fat: 1.2, unit: 'medium' },
  { name: 'Papaya', calories: 55, protein: 0.5, carbs: 14, fat: 0.3, unit: 'cup' },
  { name: 'Wheat Roti', calories: 100, protein: 3, carbs: 20, fat: 1, unit: 'medium' },
  { name: 'Rava Upma', calories: 180, protein: 4, carbs: 32, fat: 4, unit: 'cup' },
  { name: 'Poha', calories: 270, protein: 6, carbs: 52, fat: 3, unit: 'cup' },
  { name: 'Dosa', calories: 133, protein: 2.6, carbs: 26, fat: 2, unit: 'medium' },
  { name: 'Idli', calories: 130, protein: 4, carbs: 27, fat: 0.4, unit: '2 pieces' },
  { name: 'Uttapam', calories: 200, protein: 4, carbs: 30, fat: 6, unit: 'medium' },
  { name: 'Masala Dosa', calories: 387, protein: 7, carbs: 77, fat: 5.6, unit: 'medium' },
  { name: 'Sambar', calories: 110, protein: 3, carbs: 20, fat: 2, unit: 'cup' },
  { name: 'Rasam', calories: 75, protein: 2, carbs: 15, fat: 1, unit: 'cup' },
  { name: 'Avial', calories: 150, protein: 3, carbs: 10, fat: 12, unit: 'cup' },
  { name: 'Bisi Bele Bath', calories: 200, protein: 6, carbs: 40, fat: 2, unit: 'cup' },
  { name: 'Vada', calories: 125, protein: 4, carbs: 20, fat: 4, unit: '1 piece' },
  { name: 'Medu Vada', calories: 100, protein: 3, carbs: 15, fat: 4, unit: '1 piece' },
  { name: 'Rava Dosa', calories: 160, protein: 4, carbs: 24, fat: 6, unit: 'medium' },
  { name: 'Appam', calories: 160, protein: 2, carbs: 22, fat: 7, unit: '1 piece' },
  { name: 'Puttu', calories: 150, protein: 4, carbs: 33, fat: 1, unit: '1 piece' },
  { name: 'Vangi Bath', calories: 280, protein: 6, carbs: 50, fat: 6, unit: 'cup' },
  { name: 'Puliyodarai', calories: 350, protein: 6, carbs: 70, fat: 7, unit: 'cup' },
  { name: 'Lemon Pickle', calories: 50, protein: 0.5, carbs: 10, fat: 1, unit: 'tbsp' },
  { name: 'Mango Pickle', calories: 25, protein: 0.3, carbs: 6, fat: 0.2, unit: 'tbsp' },
  { name: 'Tamarind Rice', calories: 400, protein: 7, carbs: 80, fat: 8, unit: 'cup' },
  { name: 'Curd Rice', calories: 180, protein: 3, carbs: 30, fat: 5, unit: 'cup' },
  { name: 'Ragi Mudai', calories: 137, protein: 5.3, carbs: 26, fat: 1.9, unit: '100g' },
  { name: 'Biryani', calories: 250, protein: 6, carbs: 35, fat: 10, unit: 'cup' },
  { name: 'Butter Chicken', calories: 360, protein: 34, carbs: 9, fat: 22, unit: 'cup' },
  { name: 'Chicken Tikka Masala', calories: 330, protein: 20, carbs: 12, fat: 23, unit: 'cup' },
  { name: 'Palak Paneer', calories: 150, protein: 10, carbs: 8, fat: 10, unit: 'cup' },
  { name: 'Chole Bhature', calories: 450, protein: 11, carbs: 60, fat: 18, unit: 'plate' },
  { name: 'Rajma Chawal', calories: 325, protein: 12, carbs: 55, fat: 6, unit: 'cup' },
  { name: 'Pani Puri', calories: 180, protein: 3, carbs: 15, fat: 10, unit: '6 pieces' },
  { name: 'Bhel Puri', calories: 285, protein: 5, carbs: 40, fat: 12, unit: 'cup' },
  { name: 'Chicken Biryani', calories: 380, protein: 20, carbs: 50, fat: 12, unit: 'cup' },
  { name: 'Rasmalai', calories: 220, protein: 5, carbs: 18, fat: 14, unit: '1 piece' },
  { name: 'Gulab Jamun', calories: 150, protein: 2, carbs: 22, fat: 6, unit: '1 piece' },
  { name: 'Jalebi', calories: 150, protein: 2, carbs: 30, fat: 5, unit: '1 piece' },
  { name: 'Lassi', calories: 150, protein: 6, carbs: 20, fat: 4, unit: 'glass' },
  { name: 'Masala Chai', calories: 150, protein: 2, carbs: 12, fat: 9, unit: 'cup' },
  { name: 'Filter Coffee', calories: 80, protein: 1, carbs: 14, fat: 1, unit: 'cup' },
  { name: 'Thair Sadam', calories: 200, protein: 5, carbs: 40, fat: 3, unit: 'cup' },
  { name: 'Coconut Chutney', calories: 60, protein: 0.6, carbs: 4, fat: 5.5, unit: '2 tablespoons' },
  { name: 'Tomato Chutney', calories: 40, protein: 0.8, carbs: 9, fat: 0.4, unit: '2 tablespoons' },
  { name: 'Tamarind Chutney', calories: 80, protein: 0.5, carbs: 20, fat: 0.5, unit: '2 tablespoons' },
  { name: 'Raita', calories: 70, protein: 3, carbs: 6, fat: 3, unit: '1/2 cup' },
  { name: 'Upma', calories: 220, protein: 4, carbs: 38, fat: 6, unit: 'cup' },
  { name: 'Lemon Rice', calories: 200, protein: 4, carbs: 40, fat: 4, unit: 'cup' },
  { name: 'Pongal', calories: 300, protein: 8, carbs: 50, fat: 6, unit: 'cup' },
  { name: 'Bisibele Bath', calories: 350, protein: 9, carbs: 60, fat: 7, unit: 'cup' },
];